### ISSUE TITLE
regexp tests only one timestamp

### ISSUE THREAD

**Issue by heikkil** [justintaft/org-clock-split#6]
The org rexexp you are using, org-ts-regexp-both,  only tests a timestamp. You should be using org-tr-regexp or org-tr-regexp-both. Even then you are not testing the "CLOCK:" string in front of the range.

As response to an Emacs StackExchange question, I wrote a function that does the opposite of your function, i.e. megres clock lines. See https://gist.github.com/heikkil/76e8fbae3fbf6599870e6c0ca1f3c62b

If you want to combine these two into a MELPA package, that would be great. They complement each other nicely.

**Comment by miguelmorin** [comment]
This is more than an enhancement request: it is a bug. Set point on the first entry such as:

<pre>
CLOCK: [2019-12-14 Sat 08:44]
CLOCK: [2019-12-14 Sat 08:20]--[2019-12-14 Sat 08:44] =>  0:24
<pre>

and run `(org-clock-split 0h20)`. The result is:

<pre>
CLOCK: [2019-12-14 Sat 08:44]
CLOCK: [2019-12-14 Sat 08:44]
CLOCK: [2019-12-14 Sat 08:20]--[2019-12-14 Sat 09:04] =>  0:44
CLOCK: [2019-12-14 Sat 09:04]--[2019-12-13 Fri 09:21] => -23:43
</pre>

I am refactoring the code to separate the function that does reading and writing from a function that does pure string processing. This repo seems unresponsive since August 2018 and the pull request from [my fork](https://github.com/miguelmorin/org-clock-split/) has been open since April. I was the one who asked that question on StackExchange that prompted your `org-clock-merge`. I am interested in combining both of these into a package, and also addressing #4 and #5.

@heikkil Game on?

**Comment by justintaft** [comment]
@heikkil @miguelmorin I apologize for not being active, especially since you took time to write code. I'll review the changes and merge them in tomorrow. If one of you would like to be a maintainer, I don't mind transferring the project.

**Comment by justintaft** [comment]
I have merged @miguelmorin PR for checking of "CLOCK".  I'll open a new issue for the feature request of  merging of entries as proposed by @heikkil .

**Comment by miguelmorin** [comment]
I'm up for being a maintainer or receiving the transfer of the project, as you prefer.
