### ISSUE TITLE
Add feature to merge clock entries

### ISSUE THREAD

**Issue by justintaft** [justintaft/org-clock-split#9]
@heikkil and @miguelmorin  worked on code to merge clock lines. Need to merge the following code into the repository. 

https://gist.github.com/heikkil/76e8fbae3fbf6599870e6c0ca1f3c62b

**Comment by justintaft** [comment]
May I ask what your use cases are? I'm worried someone may accidentally merge clock entries which are far apart and not notice.

Would a defvar defining the  allowed maximum amount of time between two clock entries be sufficient? This way you can specify "5m", and it will fail if the clock entries are more than 5 minutes apart. 

Prompting could work too, as @miguelmorin demonstrated.

**Comment by miguelmorin** [comment]
I often work on ELISP code for which I need to restart Emacs, then develop more code. When I clock in and out, my code checks whether the discrepancy is smaller than 5 minutes, and merges automatically, otherwise it prompts for confirmation before merging.

I also use clock merging if I don't restart Emacs as a replacement for Org's feature of resolving idle time, which I never got my head around. I clock in and out of a task, then clock in on another. One hour later I realize that I spent 10 minutes on the earlier task, so I split it with my version of your code and merge it with my version of heikkil's code.

Yes `defvar` sounds good and users can override it with `setq` after loading or their own `defvar` before loading.

Does that answer your question?

**Comment by alphapapa** [comment]
I looked at the gist and see code that manually parses and diffs timestamps.  I recommend using https://github.com/alphapapa/ts.el, which will ease parsing and comparing timestamps.

**Comment by justintaft** [comment]
Thanks for the clarification @miguelmorin.

@alphapapa your library looks useful! Do you know if there is a way to lock dependencies to a certain commit? I generally review any new code before I use it in my environment.

**Comment by alphapapa** [comment]
@justintaft You may be able to do that in your personal Emacs config using tools like `straight`, but you can't control what versions users of your package install, other than setting the minimum version of dependencies in the package headers.

The purpose of `ts` is to be a useful, stable library for other Emacs packages.  I won't be breaking it carelessly.  ;)
